inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - vendor/**/*
    - db/**/*
    - bin/**
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 128

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Rails/HasAndBelongsToMany:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 10

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'

Style/RedundantSelf:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/ExtraSpacing:
  AllowForAlignment: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
